name: Build Production

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Copy .env
      run: cp .env.production .env
    - name: Install Dependencies
      run: docker-compose exec ld-php composer install
