name: Build Production

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted
    steps:
    - name: Default user
      run: whoami
    - uses: actions/checkout@v2
    - name: Copy .env
      run: cp .env.production .env
    
    - name: Install dependencies
      uses: php-actions/composer@v6
      with: 
        dev: no
        args: --profile --ignore-platform-reqs

    - name: Build & deploy containers
      run: |
        docker-compose stop 
        docker-compose build
        docker-compose start

